#
#   Makefile for SCALER
#
#   Copyright(c) 2004-2006, Samsung Electronics, Co., Ltd.
#

#s3c_tvout-y := s3c-tvscaler.0 s3c-tvenc.o
obj-$(CONFIG_VIDEO_SCALER)   	:= s3c-tvscaler.o

EXTRA_CFLAGS += -Idrivers/media/video
