#
# Makefile for the s3c framebuffer driver
#

obj-$(CONFIG_FB_S3C)		+= s3cfb.o
obj-$(CONFIG_FB_S3C)		+= s3cfb_spi.o
obj-$(CONFIG_PLAT_S3C64XX)	+= s3cfb_fimd4x.o
obj-$(CONFIG_FB_S3C_LTE480WV)	+= s3cfb_lte480wv.o
obj-$(CONFIG_FB_S3C_LTV350QV)	+= s3cfb_ltv350qv.o
obj-$(CONFIG_FB_S3C_LTS222QV)	+= s3cfb_lts222qv.o
obj-$(CONFIG_FB_S3C_AT272)	+= s3cfb_at272.o
obj-$(CONFIG_FB_S3C_PICTURETUBES) += s3cfb_picturetubes.o 
obj-$(CONFIG_FB_S3C_PICTURETUBES) += s3cfb_picturetubes_spi.o
