# S3c64XX Platform Support
snd-soc-s3c-objs := s3c-pcm.o
snd-soc-s3c64xx-ac97-objs := s3c64xx-ac97.o
snd-soc-s3c6410-i2s-objs := s3c6410-i2s-v40.o
snd-soc-s5p6440-i2s-objs := s5p6440-i2s-v40.o
snd-soc-s3c6410-i2s-v32-objs := s3c6410-i2s-v32.o

obj-$(CONFIG_SND_S3C64XX_SOC) += snd-soc-s3c.o
obj-$(CONFIG_SND_S5P64XX_SOC) += snd-soc-s3c.o
obj-$(CONFIG_SND_S3C6410_SOC_AC97) += snd-soc-s3c64xx-ac97.o
obj-$(CONFIG_SND_S3C6410_SOC_I2S) += snd-soc-s3c6410-i2s.o
obj-$(CONFIG_SND_S5P6440_SOC_I2S) += snd-soc-s5p6440-i2s.o
obj-$(CONFIG_SND_S3C6410_SOC_I2S_V32) += snd-soc-s3c6410-i2s-v32.o

# S3C24XX Machine Support
snd-soc-neo1973-wm8753-objs := neo1973_wm8753.o
snd-soc-smdk64xx-wm9713-objs := smdk64xx_wm9713.o
snd-soc-smdk6410-wm8580-objs := smdk6410_wm8580.o
snd-soc-smdk6440-wm8580-objs := smdk6440_wm8580.o
snd-soc-smdk6410-wm8990-objs := smdk6410_wm8990.o
snd-soc-smdk6410-s5m8751-objs := smdk6410_s5m8751.o

obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM9713) += snd-soc-smdk64xx-wm9713.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8580) += snd-soc-smdk6410-wm8580.o
obj-$(CONFIG_SND_S5P64XX_SOC_SMDK6440_WM8580) += snd-soc-smdk6440-wm8580.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8990) += snd-soc-smdk6410-wm8990.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_S5M8751) += snd-soc-smdk6410-s5m8751.o
